// *** TODO ***
export const TODO_GETALL_REQUEST = "TODO_GETALL_REQUEST"
export const TODO_GETALL_SUCCESS = "TODO_GETALL_SUCCESS"
export const TODO_GETALL_REJECT = "TODO_GETALL_REJECT"

export const TODO_ADD_REQUEST = "TODOS_ADD_REQUEST";
export const TODO_ADD_SUCCESS = "TODOS_ADD_SUCCESS";
export const TODO_ADD_REJECT = "TODOS_ADD_REJECT";

export const TODO_UPDATE_SET = "TODO_UPDATE_SET"
export const TODO_UPDATE_REQUEST = "TODO_UPDATE_REQUEST";
export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS";
export const TODO_UPDATE_REJECT = "TODO_UPDATE_REJECT";

export const TODO_REMOVE_REQUEST = "TODO_REMOVE_REQUEST"
export const TODO_REMOVE_SUCCESS = "TODO_REMOVE_SUCCESS"
export const TODO_REMOVE_REJECT = "TODO_REMOVE_REJECT"
